### PR TITLE
Refer to trello-smooth-dnd as the drag-n-drop core library

### PR DESCRIPTION
**Pull request by rcdexta**
@dapi I have published smooth-dnd as a package to npm for each distribution. pls review and merge if you don't see any issues

### CODE REVIEW

**Comment by alexandrakollarova** [comment]
@dapi hi, can you merge the commit anytime soon pls? Thanks!

**Comment by dapi** [comment]
Hi everybody! Give one day to check

**Comment by dapi** [comment]
👍

**Comment by alexandrakollarova** [comment]
Thanks @dapi! @rcdexta are you going to swap smooth-dnd dependency for this new trello-smooth-dnd in react-trello package? I see it's not updated yet.. let me know pls

**Pull request merged**
